name             'aar'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures aar'
long_description 'Installs/Configures aar'
version          '0.1.0'

depends          'apt'
depends          'ark'
depends          'python'
depends          'database'
depends          'mysql2_chef_gem'
